### PR TITLE
Add global hot key support

### PR DESCRIPTION
**Pull request by gusmd**

### CODE REVIEW

**Comment by liquidforce134** [comment]
Is it added?

**Comment by gusmd** [comment]
@liquidforce134 Check out the releases; v3.0 contains it.

**Comment by liquidforce134** [comment]
I did but it isn't working for me. It just gives me a PID error in the cmd

**Comment by liquidforce134** [comment]
I like the dark theme. Everything works, great work! Continue updating this, I will make a video this weekend on this update. Thanks!

**Comment by liquidforce134** [comment]
Are you going to add a save to the hotkeys?

**Comment by gusmd** [comment]
@liquidforce134 I hadn't thought of storing the hotkeys; good idea! That'll be my next update :)

**Comment by liquidforce134** [comment]
Alright, it works great! Also, if you ever get to it, adding another hotkey to start monitoring wouldn't be a bad idea either. Thanks!

**Pull request merged**
